export const ACTION_TYPE = {
  REGISTRATION: 'REGISTRATION',
  SEARCH: 'SEARCH',
  UPDATE_SELECTED_SEARCH_ITEM: 'UPDATE_SELECTED_SEARCH_ITEM',
  RESET_SELECTED_SEARCH_ITEM: 'RESET_SELECTED_SEARCH_ITEM',
};

export const API_ACTION_TYPE = {
  API: 'API',
  API_START: 'API_START',
  API_END: 'API_END',
  ACCESS_DENIED: 'ACCESS_DENIED',
  API_ERROR: 'API_ERROR',
};
